name: Svelte CI with Node

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - uses: actions/upload-artifact@v3
        if: env.ACT == 'false'
        with:
          name: seizuretracker
          path: build/