name: Svelte CI

on:
  push:
    tags:
      - '*'
  workflow_run:
    workflows: [ "Svelte CI" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan hlafaille.xyz >> ~/.ssh/known_hosts

      - name: Execute remote commands
        run: ssh hunter@hlafaille.xyz /pool1/ds_containers/webservices/scripts/seizuretracker/deploy-frontend.sh ${{ github.sha }}